# Generated by Django 4.2.2 on 2023-07-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='media/', verbose_name='Медиа статьи')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('tags', models.CharField(max_length=50, verbose_name='Теги статьи(через запятую)')),
                ('text', models.TextField(max_length=100000, verbose_name='Основной текст статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
