# Generated by Django 4.2.2 on 2023-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='media',
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='article_panel.photo', verbose_name='Медиа статьи'),
        ),
    ]
